name: Auto Update VLESS Profile

on:
  schedule:
    - cron: '0 */4 * * *' # Запускать робота каждые 4 часа автоматически
  workflow_dispatch: # Позволяет нажать кнопку "Запустить вручную" в панели GitHub

jobs:
  update-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run parser script
        run: python parse_vless.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add index.html
          git diff-index --quiet HEAD || git commit -m "Автообновление VLESS ключа"
          git push
